// Unified Lucide SVG icon set. No emoji or text-symbol stand-ins.
export {
  List as ViewListIcon,
  Columns3 as ViewGridIcon,
  Plus as PlusIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Calendar as CalendarIcon,
  Contact as IdentificationIcon,
  Lightbulb as LightBulbIcon,
  X as CloseIcon,
  Sparkles as SparklesIcon,
  Clipboard as ClipboardIcon,
  Check as CheckIcon,
  User as UserIcon,
  Pencil as PencilIcon,
  Trash2 as TrashIcon,
  Bot as ChatbotIcon,
  Search as SearchIcon,
  ListFilter as FilterIcon,
  Send as SendIcon,
  ArrowLeft as ArrowLeftIcon,
  Mic as MicrophoneIcon,
  Inbox as InboxIcon,
  Database as DatabaseIcon,
} from 'lucide-react';
